name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AZURE_WEBAPP_NAME: StockMonitorWebApp
  AZURE_WEBAPP_PACKAGE_PATH:  './published' 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore source/
    - name: Build
      run: dotnet build source/ --no-restore -c Release
    - name: Publish
      run: dotnet publish source/ --no-build -c Release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: secrets.AZURE_WEBAPP_PUBLISH_PROFILE
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
